// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type AcceptApplyRequest struct {
}

type AcceptApplyResponse struct {
}

type ApplyFriendItem struct {
	Id        int64  `json:"id"`
	UserId    int64  `json:"user_id"`
	FriendId  int64  `json:"friend_id"`
	Remark    string `json:"remark"`
	Nickname  string `json:"nickname"`
	Avater    string `json:"avatar"`
	CreatedAt string `json:"created_at"`
}

type ApplyFriendListResponse struct {
	Itmes []ApplyFriendItem `json:"items"`
}

type ApplyFriendRequest struct {
	ApplyId int64  `json:"apply_id"`
	Remark  string `json:"remark"`
}

type ApplyFriendResponse struct {
}

type CancelApplyRequest struct {
	Id int64 `json:"id"`
}

type CancelApplyResponse struct {
}

type RejectApplyRequest struct {
}

type RejectApplyResponse struct {
}

type RemoveFriendRequest struct {
	FriendId int64 `json:"friend_id"`
}

type RemoveFriendResponse struct {
}

type SearchFriendRequest struct {
	Mobile string `json:"mobile"`
}

type SearchFriendResponse struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Gender   int    `json:"gender"`
	Email    string `json:"email"`
	UserId   int64  `json:"user_id"`
}
