// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: email.proto

package server

import (
	"context"

	"im/application/email/rpc/internal/logic"
	"im/application/email/rpc/internal/svc"
	"im/application/email/rpc/service"
)

type EmailServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedEmailServer
}

func NewEmailServer(svcCtx *svc.ServiceContext) *EmailServer {
	return &EmailServer{
		svcCtx: svcCtx,
	}
}

func (s *EmailServer) SendEmail(ctx context.Context, in *service.SendEmailRequest) (*service.SendEmailResponse, error) {
	l := logic.NewSendEmailLogic(ctx, s.svcCtx)
	return l.SendEmail(in)
}

func (s *EmailServer) CheckEmail(ctx context.Context, in *service.CheckEmailCodeRequest) (*service.CheckEmailCodeResponse, error) {
	l := logic.NewCheckEmailLogic(ctx, s.svcCtx)
	return l.CheckEmail(in)
}

func (s *EmailServer) DeleteEmailCode(ctx context.Context, in *service.DeleteEmailCodeRequest) (*service.DeleteEmailCodeResponse, error) {
	l := logic.NewDeleteEmailCodeLogic(ctx, s.svcCtx)
	return l.DeleteEmailCode(in)
}
