// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	apply "im/application/friend/api/internal/handler/apply"
	friend "im/application/friend/api/internal/handler/friend"
	"im/application/friend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/apply",
				Handler: apply.ApplyFriendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/apply",
				Handler: apply.ApplyFriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/apply",
				Handler: apply.CancelApplyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: apply.SearchFriendHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/friend"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/remove",
				Handler: friend.RemoveFriendHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/friend"),
	)
}
